apiVersion: v1
kind: Secret
metadata:
  name: rag-backend-secrets
type: Opaque
stringData:
  GROQ_API_KEY: "your_key"
  QDRANT_URL: "your_qdrant_url"
  QDRANT_API_KEY: "your_qdrant_key"
  HF_TOKEN: "your_hf_token"
  DOCS_USERNAME: "admin"
  DOCS_PASSWORD: "your_password"